### ISSUE TITLE
CodeDeploy hanging in `dev`

### ISSUE THREAD

**Issue by GaryGSC** [byu-oit/hw-fargate-api#242]
We recently bumped the `terraform-aws-postman-test-lambda` here ([#240](https://github.com/byu-oit/hw-fargate-api/pull/240/files#diff-4a41ce2be7323ec3f381c7175eb96df6d7a11e5271a76f37461d7c5e1dfdfaa4R212-R223)), which [caused CodeDeploy to hang](https://github.com/byu-oit/hw-fargate-api/runs/2859573422) on the AfterAllowTestTraffic lambda because it had trouble getting either the collection or the environment from the S3 bucket:
```
INFO	started download for ../../../.postman/hw-fargate-api.postman_collection.json from s3 bucket
INFO	started download for ../../../.postman/dev-tst.postman_environment.json from s3 bucket
ERROR	error trying to get object from bucket: BadRequest: null
ERROR	Invoke Error 	
{
    "errorType": "BadRequest",
    "errorMessage": null,
    "code": "BadRequest",
    "message": null,
    "region": "us-west-2",
    "time": "2021-06-18T15:09:26.073Z",
    "requestId": "AGMDXXJSB55XW3NK",
    "extendedRequestId": "WZj4PYX3RvsathkpIPFQV8RkSRA1h+656Nv/5mE62+M1ZVEF57cfa7J7BmBGzG7iFKFpJAUIE3k=",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 65.10930885255566,
    "stack": [
        "BadRequest: null",
        "    at Request.extractError (/var/task/index.js:1:6656226)",
        "    at Request.callListeners (/var/task/index.js:1:9583241)",
        "    at Request.emit (/var/task/index.js:1:9582892)",
        "    at Request.emit (/var/task/index.js:1:2516985)",
        "    at Request.e (/var/task/index.js:1:2512160)",
        "    at AcceptorStateMachine.runTo (/var/task/index.js:1:5700974)",
        "    at /var/task/index.js:1:5701188",
        "    at Request.<anonymous> (/var/task/index.js:1:2512393)",
        "    at Request.<anonymous> (/var/task/index.js:1:2517040)",
        "    at Request.callListeners (/var/task/index.js:1:9583345)",
        "    at Request.emit (/var/task/index.js:1:9582892)",
        "    at Request.emit (/var/task/index.js:1:2516985)",
        "    at Request.e (/var/task/index.js:1:2512160)",
        "    at AcceptorStateMachine.runTo (/var/task/index.js:1:5700974)",
        "    at /var/task/index.js:1:5701188",
        "    at Request.<anonymous> (/var/task/index.js:1:2512393)"
    ]
}
```

**Comment by GaryGSC** [comment]
Closed via #243.
